export const REQUEST_TYPES = {
  INIT: "INIT",
  GENERATE: "GENERATE",
  ABORT: "ABORT",
};

export const RESPONSE_TYPES = {
  READY: "READY",
  TOKEN: "TOKEN",
  DONE: "DONE",
  ERROR: "ERROR",
  STATUS: "STATUS",
  BANNER: "BANNER",
};

export const ERROR_ACTIONS = {
  RESTART_WASM: "RESTART_WASM",
};
